import "./index.css";
import { SidebarContextProvider } from "./components/context/SidebarContext";
import Navbar from "./components/Navbar/Navbar";
import { SubContextProvider } from "./components/context/SubContext";
import { BrowserRouter, Routes, Route } from "react-router-dom";
import Job from "./pages/Job/Job";
import JobDescription from "./pages/JobDescprition/JobDescprition";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <SubContextProvider>
        <SidebarContextProvider>
          <BrowserRouter>
            {<Navbar /> }
            <Routes>
              <Route path='/'  />
              <Route path='/jobs' element={<Job/>} />
              <Route path='/jobs/:id' element={<JobDescription/>} />
            </Routes>
          </BrowserRouter>
        </SidebarContextProvider>
      </SubContextProvider>
    </html>
  );
}
